include:
  - homepage/docker-compose.yml
  # - plex/docker-compose.yml          # disabled - using Stremio + RealDebrid
  # - prowlarr/docker-compose.yml      # disabled - using Stremio + RealDebrid
  # - radarr/docker-compose.yml        # disabled - using Stremio + RealDebrid
  # - sonarr/docker-compose.yml        # disabled - using Stremio + RealDebrid
  # - transmission/docker-compose.yml  # disabled - using Stremio + RealDebrid
  - nginx-proxy-manager/docker-compose.yml
  - pihole/docker-compose.yml
  - vaultwarden/docker-compose.yml
  - uptime-kuma/docker-compose.yml
  # - immich/docker-compose.yml            # disabled - hardware requirements not met (min 6GB RAM)

