include:
  - homepage/docker-compose.yml
  - plex/docker-compose.yml
  - prowlarr/docker-compose.yml
  - radarr/docker-compose.yml
  - sonarr/docker-compose.yml
  - transmission/docker-compose.yml
  - nginx-proxy-manager/docker-compose.yml
  - pihole/docker-compose.yml
  - immich/docker-compose.yml

