---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/
          icon: github.png
    - AWS:
        - abbr: AW
          href: https://console.aws.amazon.com/
          icon: aws.png
    - Python:
        - abbr: PY
          href: https://docs.python.org/
          icon: python.png

- AI:
    - Claude:
        - abbr: CL
          href: https://claude.ai/
          icon: claude-ai.png
    - ChatGPT:
        - abbr: GP
          href: https://chatgpt.com/
          icon: chatgpt.png
    - Gemini:
        - abbr: GM
          href: https://gemini.google.com/
          icon: google-gemini.png

- Media:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
          icon: youtube.png
    - Reddit:
        - abbr: RE
          href: https://reddit.com/
          icon: reddit.png
    - Linkedin:
        - abbr: LI
          href: https://linkedin.com/
          icon: linkedin.png
    - Facebook:
        - abbr: FB
          href: https://facebook.com/
          icon: facebook.png
    - Instagram:
        - abbr: IG
          href: https://instagram.com/
          icon: instagram.png
